name: grpc_bug_reproduce_client_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

flutter:
  uses-material-design: true

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # High performance, open-source universal RPC framework
  grpc: ^3.0.2
  # Provides runtime support for a Dart implementation of protobufs.
  protobuf: ^2.1.0
  # Extends the capabilities of Dart Streams and StreamControllers.
  rxdart: ^0.27.5

dev_dependencies:
  flutter_lints: ^2.0.1
  lints: ^2.0.0
  test: ^1.21.4

